spring:
  application:
    name: mivas

  datasource:
    url: jdbc:postgresql://localhost:5432/masterdb  # banco master
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: MasterPool

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

mivas:
  security:
    secret: 5454211844848asd4wwd4w

logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    dev.enterprisemanager: DEBUG
