spring:
  application:
    name: mivas

  datasource:
    url: jdbc:postgresql://localhost:5432/enterpriseDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

mivas:
  security:
    secret: 5454211844848asd4wwd4w
logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    dev.enterprisemanager: DEBUG
